eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
spring:
  application:
    name: station
openWeatherApiKey: xxx
redis:
  insertionType: NX
  expirationType: EX
  expiresIn: 3600

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
