eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
spring:
  application:
    name: station
openWeatherApiKey: xxx
redis:
  insertionType: NX
  expirationType: EX
  expiresIn: 3600
