eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
server:
  port: 8765
spring:
  application:
    name: morannon
zuul:
  routes:
    weather:
      path: /weather**
      serviceId: station