eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
server:
  port: 8765
spring:
  application:
    name: morannon

zuul:
  routes:
    weather:
      path: /weather**
      serviceId: station

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000