eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
server:
  port: 8765
spring:
  application:
    name: morannon

zuul:
  routes:
    weather:
      path: /weather**
      serviceId: station

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000